### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by kpym** [mmalcek/bafi#2]
When I try to install bafi with `go install github.com/mmalcek/bafi@latest` there is an error:
```
go: downloading github.com/mmalcek/bafi v1.0.13
go install: github.com/mmalcek/bafi@latest: github.com/mmalcek/bafi@v1.0.13: parsing go.mod:
        module declares its path as: bafi
                but was required as: github.com/mmalcek/bafi
```

Probably you could simply rename `bafi` to `github.com/mmalcek/bafi` in `go.mod` ?

**Comment by mmalcek** [comment]
Hi, you are right - i've just fixed it in v.1.0.14 (no other changes). It should work now
